### ISSUE TITLE
Sampler?

### ISSUE THREAD

**Issue by Charlie110** [edoliberty/streaming-quantiles#3]
Dear Author Liberty,
Thank you so much for providing the KLL sketch codes. In the "Optimal Quantile Approximation in Streams" and "Streaming Quantiles Algorithms" they both talked about replace the log(n) stack of compactors of capacity 2 with a sampler. I have serveral questions regarding the sampler.
If without sampler, will KLL becomes a deterministic algorithm?
In this implementation, sampler are not included?

With Many Thanks!

**Comment by edoliberty** [comment]
Evan without the sampler the algorithm is not deterministic.
This implementation does not include the samplers.

Regardless, this is a research project... You should look to apache-datasketches for the official implementation. 
https://github.com/apache/datasketches-java
